version: '3'
services:
  db:
    image: postgres:15.3-alpine
    restart: always
    tty: true
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - .data:/var/lib/postgresql/data
      - ./sql:/migration
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ride-app